PROJECT_TARGET = FRC_UserProgram.out
PROJECT_OBJECTS = FRC_UserProgram.o

ADDED_INCLUDES = -I../Packages/wpilib/WPILib -I../RobotPy/Python

override DISTDIR := $(DISTDIR)/robot/ni-rt/system/

include ../mk/module.mk
