.PHONY: all

all:
	$(MAKE) -C _bisect
	$(MAKE) -C _collections
	$(MAKE) -C _csv
	$(MAKE) -C _elementtree
	$(MAKE) -C _heapq
	$(MAKE) -C _md5
	$(MAKE) -C _pickle
	$(MAKE) -C _random
	$(MAKE) -C _sha1
	$(MAKE) -C _sha256
	$(MAKE) -C _sha512
	$(MAKE) -C _socket
	$(MAKE) -C _struct
	$(MAKE) -C array
	$(MAKE) -C atexit
	$(MAKE) -C binascii
	$(MAKE) -C cmath
	$(MAKE) -C datetime
	$(MAKE) -C fcntl
	$(MAKE) -C fpectl
	$(MAKE) -C itertools
	$(MAKE) -C math
	$(MAKE) -C operator
	$(MAKE) -C parser
	$(MAKE) -C pyexpat
	$(MAKE) -C readline
	$(MAKE) -C select
	$(MAKE) -C time
	$(MAKE) -C unicodedata
	$(MAKE) -C zlib

