# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = "robotpy-builder"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "hashicorp/precise64"
  
  # mount the robotpy source code in the home directory
  config.vm.synced_folder "..", "/home/vagrant/robotpy"

  # Shell provisioner to install prerequisites -- requires internet access!
  config.vm.provision "shell", path: "install_toolchain.sh"
  config.vm.provision "shell", inline: "apt-get install -y git"
  config.vm.provision "shell", path: "install_sip.sh"


end
