# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin "vagrant-berkshelf"

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = "robotpy-builder"

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  
  # Use berkshelf to find cookbooks
  config.berkshelf.enabled = true
  
  # mount the robotpy source code in the home directory
  config.vm.synced_folder "..", "/home/vagrant/robotpy"

  config.vm.provision :chef_solo do |chef|
    
    chef.run_list = [
      "recipe[apt]",
      "recipe[frc-gcc-vm]",
      "recipe[python-sip]",
      "recipe[git]",
    ]
  end
end
