
set(CPACK_GENERATOR ZIP)
set(CPACK_PACKAGE_VERSION_MAJOR ${ROBOTPY_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${ROBOTPY_VERSION_MINOR})
set(CPACK_PACKAGE_FILE_NAME RobotPy-${ROBOTPY_VERSION})
set(CPACK_INCLUDE_TOPLEVEL_DIRECTORY 1)

